# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Tk-JComboBox
version:      1.08
version_from: lib/Tk/JComboBox.pm
installdirs:  site
requires:
    Tk:                            800.024

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
